"""create programme dependencies table

Revision ID: 22d37aa08109
Revises: 3f23c72d06b1
Create Date: 2026-07-20 23:08:34.656200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22d37aa08109'
down_revision: Union[str, Sequence[str], None] = '3f23c72d06b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('programme_dependencies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('predecessor_id', sa.Uuid(), nullable=False),
    sa.Column('successor_id', sa.Uuid(), nullable=False),
    sa.Column('dependency_type', sa.String(length=2), server_default='FS', nullable=False),
    sa.Column('lag_minutes', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('predecessor_id <> successor_id', name='ck_programme_dependency_not_self'),
    sa.ForeignKeyConstraint(['predecessor_id'], ['programme_activities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['successor_id'], ['programme_activities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('predecessor_id', 'successor_id', 'dependency_type', name='uq_programme_dependency')
    )
    op.create_index(op.f('ix_programme_dependencies_predecessor_id'), 'programme_dependencies', ['predecessor_id'], unique=False)
    op.create_index(op.f('ix_programme_dependencies_successor_id'), 'programme_dependencies', ['successor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_programme_dependencies_successor_id'), table_name='programme_dependencies')
    op.drop_index(op.f('ix_programme_dependencies_predecessor_id'), table_name='programme_dependencies')
    op.drop_table('programme_dependencies')
    # ### end Alembic commands ###
