"""create programme activities table

Revision ID: 3f23c72d06b1
Revises: a01c23009cf8
Create Date: 2026-07-20 23:04:01.962191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f23c72d06b1'
down_revision: Union[str, Sequence[str], None] = 'a01c23009cf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('programme_activities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('programme_revision_id', sa.Uuid(), nullable=False),
    sa.Column('work_package_id', sa.Uuid(), nullable=True),
    sa.Column('activity_code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('activity_type', sa.String(length=50), server_default='task', nullable=False),
    sa.Column('external_id', sa.String(length=150), nullable=True),
    sa.Column('planned_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('planned_finish', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('percent_complete', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_milestone', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('status', sa.String(length=30), server_default='not_started', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('percent_complete >= 0 AND percent_complete <= 100', name='ck_programme_activity_percent_complete'),
    sa.ForeignKeyConstraint(['programme_revision_id'], ['programme_revisions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_package_id'], ['work_packages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('programme_revision_id', 'activity_code', name='uq_programme_activity_revision_code')
    )
    op.create_index(op.f('ix_programme_activities_programme_revision_id'), 'programme_activities', ['programme_revision_id'], unique=False)
    op.create_index(op.f('ix_programme_activities_work_package_id'), 'programme_activities', ['work_package_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_programme_activities_work_package_id'), table_name='programme_activities')
    op.drop_index(op.f('ix_programme_activities_programme_revision_id'), table_name='programme_activities')
    op.drop_table('programme_activities')
    # ### end Alembic commands ###
