"""create deliverables table

Revision ID: 57c66c1f088c
Revises: 4fa0ce7005bf
Create Date: 2026-07-20 22:19:23.853324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57c66c1f088c'
down_revision: Union[str, Sequence[str], None] = '4fa0ce7005bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deliverables',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('work_package_id', sa.Uuid(), nullable=False),
    sa.Column('reference', sa.String(length=150), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('deliverable_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='not_started', nullable=False),
    sa.Column('planned_issue_date', sa.Date(), nullable=True),
    sa.Column('required_approval_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['work_package_id'], ['work_packages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('work_package_id', 'reference', name='uq_deliverables_package_reference')
    )
    op.create_index(op.f('ix_deliverables_work_package_id'), 'deliverables', ['work_package_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deliverables_work_package_id'), table_name='deliverables')
    op.drop_table('deliverables')
    # ### end Alembic commands ###
