"""create deliverable revisions table

Revision ID: 6364c9a94ca6
Revises: 57c66c1f088c
Create Date: 2026-07-20 22:26:30.212804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6364c9a94ca6'
down_revision: Union[str, Sequence[str], None] = '57c66c1f088c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deliverable_revisions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('deliverable_id', sa.Uuid(), nullable=False),
    sa.Column('revision_code', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), server_default='draft', nullable=False),
    sa.Column('issue_purpose', sa.String(length=50), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['deliverable_id'], ['deliverables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deliverable_id', 'revision_code', name='uq_revision_deliverable_code')
    )
    op.create_index(op.f('ix_deliverable_revisions_deliverable_id'), 'deliverable_revisions', ['deliverable_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deliverable_revisions_deliverable_id'), table_name='deliverable_revisions')
    op.drop_table('deliverable_revisions')
    # ### end Alembic commands ###
