"""create programme calendars

Revision ID: 916e9c81163d
Revises: 9754f3190dfc
Create Date: 2026-07-20 23:25:19.861970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '916e9c81163d'
down_revision: Union[str, Sequence[str], None] = '9754f3190dfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('programme_calendars',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('programme_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('timezone', sa.String(length=100), server_default='UTC', nullable=False),
    sa.Column('standard_day_minutes', sa.Integer(), server_default='480', nullable=False),
    sa.Column('weekly_schedule', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_default', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('status', sa.String(length=30), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['programme_id'], ['programmes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('programme_id', 'name', name='uq_programme_calendar_name')
    )
    op.create_index(op.f('ix_programme_calendars_programme_id'), 'programme_calendars', ['programme_id'], unique=False)
    op.create_index('uq_programme_calendar_default', 'programme_calendars', ['programme_id'], unique=True, postgresql_where=sa.text('is_default = true'))
    op.create_table('programme_calendar_exceptions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('calendar_id', sa.Uuid(), nullable=False),
    sa.Column('exception_date', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('exception_type', sa.String(length=50), server_default='holiday', nullable=False),
    sa.Column('is_working_day', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('working_periods', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['calendar_id'], ['programme_calendars.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('calendar_id', 'exception_date', name='uq_programme_calendar_exception_date')
    )
    op.create_index(op.f('ix_programme_calendar_exceptions_calendar_id'), 'programme_calendar_exceptions', ['calendar_id'], unique=False)
    op.add_column('programme_activities', sa.Column('calendar_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_programme_activities_calendar_id'), 'programme_activities', ['calendar_id'], unique=False)
    op.create_foreign_key('fk_programme_activities_calendar_id', 'programme_activities', 'programme_calendars', ['calendar_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_programme_activities_calendar_id', 'programme_activities', type_='foreignkey')
    op.drop_index(op.f('ix_programme_activities_calendar_id'), table_name='programme_activities')
    op.drop_column('programme_activities', 'calendar_id')
    op.drop_index(op.f('ix_programme_calendar_exceptions_calendar_id'), table_name='programme_calendar_exceptions')
    op.drop_table('programme_calendar_exceptions')
    op.drop_index('uq_programme_calendar_default', table_name='programme_calendars', postgresql_where=sa.text('is_default = true'))
    op.drop_index(op.f('ix_programme_calendars_programme_id'), table_name='programme_calendars')
    op.drop_table('programme_calendars')
    # ### end Alembic commands ###
