"""create programme baselines and imports tables

Revision ID: 9754f3190dfc
Revises: 22d37aa08109
Create Date: 2026-07-20 23:15:30.448042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9754f3190dfc'
down_revision: Union[str, Sequence[str], None] = '22d37aa08109'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('programme_baselines',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('programme_id', sa.Uuid(), nullable=False),
    sa.Column('source_revision_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('baseline_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=30), server_default='active', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['programme_id'], ['programmes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_revision_id'], ['programme_revisions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('programme_id', 'name', name='uq_programme_baseline_name')
    )
    op.create_index(op.f('ix_programme_baselines_programme_id'), 'programme_baselines', ['programme_id'], unique=False)
    op.create_index(op.f('ix_programme_baselines_source_revision_id'), 'programme_baselines', ['source_revision_id'], unique=False)
    op.create_table('programme_imports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('programme_id', sa.Uuid(), nullable=False),
    sa.Column('programme_revision_id', sa.Uuid(), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_filename', sa.String(length=255), nullable=True),
    sa.Column('source_reference', sa.String(length=255), nullable=True),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='pending', nullable=False),
    sa.Column('total_records', sa.Integer(), server_default='0', nullable=False),
    sa.Column('imported_records', sa.Integer(), server_default='0', nullable=False),
    sa.Column('warning_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('mapping_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('validation_issues', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['programme_id'], ['programmes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['programme_revision_id'], ['programme_revisions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_programme_imports_programme_id'), 'programme_imports', ['programme_id'], unique=False)
    op.create_index(op.f('ix_programme_imports_programme_revision_id'), 'programme_imports', ['programme_revision_id'], unique=False)
    op.create_table('programme_baseline_activities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('baseline_id', sa.Uuid(), nullable=False),
    sa.Column('source_activity_id', sa.Uuid(), nullable=True),
    sa.Column('work_package_id', sa.Uuid(), nullable=True),
    sa.Column('activity_code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('external_id', sa.String(length=150), nullable=True),
    sa.Column('work_package_code', sa.String(length=50), nullable=True),
    sa.Column('work_package_name', sa.String(length=200), nullable=True),
    sa.Column('planned_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('planned_finish', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('percent_complete', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_milestone', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('status', sa.String(length=30), server_default='not_started', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('percent_complete >= 0 AND percent_complete <= 100', name='ck_baseline_activity_percent_complete'),
    sa.ForeignKeyConstraint(['baseline_id'], ['programme_baselines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_activity_id'], ['programme_activities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['work_package_id'], ['work_packages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('baseline_id', 'activity_code', name='uq_baseline_activity_code')
    )
    op.create_index(op.f('ix_programme_baseline_activities_baseline_id'), 'programme_baseline_activities', ['baseline_id'], unique=False)
    op.create_index(op.f('ix_programme_baseline_activities_source_activity_id'), 'programme_baseline_activities', ['source_activity_id'], unique=False)
    op.create_index(op.f('ix_programme_baseline_activities_work_package_id'), 'programme_baseline_activities', ['work_package_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_programme_baseline_activities_work_package_id'), table_name='programme_baseline_activities')
    op.drop_index(op.f('ix_programme_baseline_activities_source_activity_id'), table_name='programme_baseline_activities')
    op.drop_index(op.f('ix_programme_baseline_activities_baseline_id'), table_name='programme_baseline_activities')
    op.drop_table('programme_baseline_activities')
    op.drop_index(op.f('ix_programme_imports_programme_revision_id'), table_name='programme_imports')
    op.drop_index(op.f('ix_programme_imports_programme_id'), table_name='programme_imports')
    op.drop_table('programme_imports')
    op.drop_index(op.f('ix_programme_baselines_source_revision_id'), table_name='programme_baselines')
    op.drop_index(op.f('ix_programme_baselines_programme_id'), table_name='programme_baselines')
    op.drop_table('programme_baselines')
    # ### end Alembic commands ###
