"""create programmes and programme revisions tables

Revision ID: a01c23009cf8
Revises: d8a94e09ed31
Create Date: 2026-07-20 22:58:24.392944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a01c23009cf8'
down_revision: Union[str, Sequence[str], None] = 'd8a94e09ed31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('programmes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), server_default='Project Programme', nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_programmes_project_id'), 'programmes', ['project_id'], unique=True)
    op.create_table('programme_revisions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('programme_id', sa.Uuid(), nullable=False),
    sa.Column('revision_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('source_type', sa.String(length=50), server_default='manual', nullable=False),
    sa.Column('source_filename', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='draft', nullable=False),
    sa.Column('is_current', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('revision_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['programme_id'], ['programmes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('programme_id', 'revision_code', name='uq_programme_revisions_code')
    )
    op.create_index(op.f('ix_programme_revisions_programme_id'), 'programme_revisions', ['programme_id'], unique=False)
    op.create_index('uq_programme_revisions_current', 'programme_revisions', ['programme_id'], unique=True, postgresql_where=sa.text('is_current = true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_programme_revisions_current', table_name='programme_revisions', postgresql_where=sa.text('is_current = true'))
    op.drop_index(op.f('ix_programme_revisions_programme_id'), table_name='programme_revisions')
    op.drop_table('programme_revisions')
    op.drop_index(op.f('ix_programmes_project_id'), table_name='programmes')
    op.drop_table('programmes')
    # ### end Alembic commands ###
