"""create approvals table

Revision ID: d8a94e09ed31
Revises: 6364c9a94ca6
Create Date: 2026-07-20 22:46:26.219020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8a94e09ed31'
down_revision: Union[str, Sequence[str], None] = '6364c9a94ca6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approvals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('revision_id', sa.Uuid(), nullable=False),
    sa.Column('approval_stage', sa.String(length=100), server_default='external_review', nullable=False),
    sa.Column('reviewer_name', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='pending', nullable=False),
    sa.Column('submitted_date', sa.Date(), nullable=True),
    sa.Column('response_due_date', sa.Date(), nullable=True),
    sa.Column('response_received_date', sa.Date(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['revision_id'], ['deliverable_revisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approvals_revision_id'), 'approvals', ['revision_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_approvals_revision_id'), table_name='approvals')
    op.drop_table('approvals')
    # ### end Alembic commands ###
